config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'home#index'
  resources :users, only: [:new, :create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :posts, only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

require 'openssl'

class User < ApplicationRecord
  attr_accessor :password, :password_confirmation

  before_save :hash_password
  validate :password_match

  validates :password, presence: true, on: :create
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def authenticate(submitted_password)
    hashed_password == OpenSSL::Digest::SHA256.hexdigest(submitted_password + salt)
  end

  def generate_token
    self.token = SecureRandom.urlsafe_base64.to_s
    save
  end

  def clear_token
    self.token = nil
    save
  end

  private

  def hash_password
    return if password.blank?

    self.salt = SecureRandom.hex
    self.hashed_password = OpenSSL::Digest::SHA256.hexdigest(password + salt)
  end

  def password_match
    errors.add(:password, "doesn't match Password confirmation") unless password == password_confirmation
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ActionController::HttpAuthentication::Token::ControllerMethods

  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_api_user
    authenticate_with_http_token do |token, _options|
      @current_user = User.find_by(token:)
    end
  end

  def logged_in?
    session[:user_id].present? || authenticate_api_user
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :require_login

  def index
    @posts = Post.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  private

  def require_login
    return if logged_in?

    respond_to do |format|
      format.html { redirect_to root_url, alert: 'You must be logged in to access this page.' }
      format.json { render json: { error: 'You must be logged in to access this page.' }, status: :unauthorized }
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[create destroy]

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      handle_user_authentication(user)
    else
      handle_authentication_failure
    end
  end

  def destroy
    if request.format.json?
      handle_api_logout
    else
      handle_html_logout
    end
  end

  private

  def handle_user_authentication(user)
    if request.format.json?
      user.generate_token
      render json: { token: user.token }, status: :ok
    else
      session[:user_id] = user.id
      redirect_to posts_path, notice: 'Logged in successfully'
    end
  end

  def handle_authentication_failure
    respond_to do |format|
      format.json { render json: { error: 'Email or password is invalid' }, status: :unauthorized }
      format.html do
        flash.now[:alert] = 'Email or password is invalid'
        render 'new', status: :unprocessable_entity
      end
    end
  end

  def handle_api_logout
    token = request.headers['Authorization']&.match(/Token token="([^"]+)"/)&.captures&.first
    user = User.find_by(token:)

    if user
      user.clear_token
      head :no_content
    else
      render json: { error: 'Invalid token or already logged out.' }, status: :unauthorized
    end
  end

  def handle_html_logout
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url, notice: 'Logged out successfully.'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      handle_successful_create
    else
      handle_failed_create
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def handle_successful_create
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully created.' }
      format.json { render json: { message: 'User was successfully created.', user: @user }, status: :created }
    end
  end

  def handle_failed_create
    respond_to do |format|
      format.html do
        flash.now[:error] = 'Please enter the data properly'
        render :new, status: :unprocessable_entity
      end
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome to the test app built with Ruby on Rails 🚀</h1>
<% if logged_in? %>
  <h2>Greetings,
    <%= current_user.email %></h2>
<% else %>
  <h2>You are not logged in yet</h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to "Home", root_path %>
      <% if logged_in? %>
        <%= link_to "Posts", posts_path %>
        <%= link_to "Log Out", logout_path, data: { turbo_method: :delete } %>
      <% else %>
        <%= link_to "Log In", login_path %>
        <%= link_to "Register", new_user_path %>
      <% end %>
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "flash #{name}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post">
      <h2><%= post.title %></h2>
      <p><%= post.content %></p>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true, required: true, class: "input" %>
  </div>

  <div class="form-field">
    <%= f.label :password %>
    <%= f.password_field :password, required: true, class: "input" %>
  </div>

  <div class="form-field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, required: true, class: "input" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign Up", class: "button" %>
  </div>
<% end %>